// Code generated by versioncli. DO NOT EDIT.
package versioning

type APIVersion struct {
	ID          string
	Description string
	Status      string
	ReleasedAt  string
}

const DefaultVersion = "2026-03-06-8338"

var Registry = map[string]APIVersion{
	"2026-03-06-8338": {
		ID:          "2026-03-06-8338",
		Description: "Initial date-based versioning release",
		Status:      "ACTIVE",
		ReleasedAt:  "2026-03-06T16:28:01+05:30",
	},
}

func IsValid(version string) bool {
	_, exists := Registry[version]
	return exists
}
