server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # URL: apps.shikshakul.com/admin
    location /admin {
        alias /usr/share/nginx/html/admin;
        try_files $uri $uri/ /admin/index.html;
    }

    # URL: apps.shikshakul.com/teacher
    location /teacher {
        alias /usr/share/nginx/html/teacher;
        try_files $uri $uri/ /teacher/index.html;
    }

    # URL: apps.shikshakul.com/parent
    location /parent {
        alias /usr/share/nginx/html/guardian;
        try_files $uri $uri/ /parent/index.html;
    }

    # --- Health Check ---
    location /health {
        return 200 "Frontend is UP";
        add_header Content-Type text/plain;
    }
}
