package main

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"text/template"
	"time"
)

const jsonPath = "../../versioning/versions.json"
const outPath = "../../versioning/registry.go"

type Version struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Status      string `json:"status"`
	ReleasedAt  string `json:"released_at"`
}

type VersionRegistry struct {
	Default  string    `json:"default"`
	Versions []Version `json:"versions"`
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: go run main.go [release|deprecate|generate] [flags]")
		os.Exit(1)
	}

	command := os.Args[1]

	switch command {
	case "release":
		releaseCmd := flag.NewFlagSet("release", flag.ExitOnError)
		desc := releaseCmd.String("desc", "New release", "Description of the release")
		releaseCmd.Parse(os.Args[2:])
		createNewRelease(*desc)
	case "deprecate":
		deprecateCmd := flag.NewFlagSet("deprecate", flag.ExitOnError)
		id := deprecateCmd.String("id", "", "Version ID to deprecate")
		deprecateCmd.Parse(os.Args[2:])
		if *id == "" {
			fmt.Println("Error: --id flag is required")
			os.Exit(1)
		}
		deprecateRelease(*id)
	case "generate":
		generateCode()
	default:
		fmt.Println("Unknown command. Use: release, deprecate, or generate")
		os.Exit(1)
	}
}

func loadRegistry() VersionRegistry {
	file, _ := os.ReadFile(jsonPath)
	var reg VersionRegistry
	json.Unmarshal(file, &reg)
	return reg
}

func saveRegistry(reg VersionRegistry) {
	data, _ := json.MarshalIndent(reg, "", "  ")
	os.WriteFile(jsonPath, data, 0644)
	fmt.Println("Updated versions.json")
}

func createNewRelease(desc string) {
	reg := loadRegistry()

	dateStr := time.Now().Format("2006-01-02")
	bytes := make([]byte, 2)
	rand.Read(bytes)
	hexStr := hex.EncodeToString(bytes)
	newID := fmt.Sprintf("%s-%s", dateStr, hexStr)

	newVer := Version{
		ID:          newID,
		Description: desc,
		Status:      "ACTIVE",
		ReleasedAt:  time.Now().Format(time.RFC3339),
	}

	reg.Versions = append(reg.Versions, newVer)
	reg.Default = newID

	saveRegistry(reg)
	generateCode()
	fmt.Printf("Created new release: %s\n", newID)
}

func deprecateRelease(id string) {
	reg := loadRegistry()
	found := false
	for i, v := range reg.Versions {
		if v.ID == id {
			reg.Versions[i].Status = "DEPRECATED"
			found = true
			break
		}
	}
	if !found {
		fmt.Printf("Version %s not found\n", id)
		return
	}
	saveRegistry(reg)
	generateCode()
	fmt.Printf("Deprecated release: %s\n", id)
}

func generateCode() {
	reg := loadRegistry()

	const codeTemplate = `// Code generated by versioncli. DO NOT EDIT.
package versioning

type APIVersion struct {
	ID          string
	Description string
	Status      string
	ReleasedAt  string
}

const DefaultVersion = "{{.Default}}"

var Registry = map[string]APIVersion{
{{- range .Versions }}
	"{{.ID}}": {
		ID:          "{{.ID}}",
		Description: "{{.Description}}",
		Status:      "{{.Status}}",
		ReleasedAt:  "{{.ReleasedAt}}",
	},
{{- end }}
}

func IsValid(version string) bool {
	_, exists := Registry[version]
	return exists
}
`
	tmpl, _ := template.New("registry").Parse(codeTemplate)
	file, _ := os.Create(outPath)
	defer file.Close()
	tmpl.Execute(file, reg)
	fmt.Println("Successfully compiled registry.go!")
}
